FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Zotes.Api/Zotes.Api.csproj", "Zotes.Api/"]
COPY ["Zotes.Persistence/Zotes.Persistence.csproj", "Zotes.Persistence/"]
COPY ["Zotes.Business/Zotes.Business.csproj", "Zotes.Business/"]
COPY ["Zotes.Domain/Zotes.Domain.csproj", "Zotes.Domain/"]
RUN dotnet restore "Zotes.Api/Zotes.Api.csproj"
COPY . .
WORKDIR "/src/Zotes.Api"
RUN dotnet build "./Zotes.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Zotes.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Zotes.Api.dll"]
